### ISSUE TITLE
request: option to disable bilinear filter?

### ISSUE THREAD

**Issue by therealteamplayer** [emukidid/pcsxgc#17]
imo, the biggest disadvantage that remains with wiisx and its forks is the ugly bilinear smear filter that is forcibly applied to everything. adding an option to disable it, along with appropriate scaling options akin to something like SNESRX, would be a huge improvement.

**Comment by saulfabregwiivc** [comment]
[WiiStation](https://github.com/xjsxjs197/WiiSXRX_2022) by @xjsxjs197 (with changes from @Jokippo) has options for toggle enabling/disabling of Bilinear, Trap and Deflicker filters.

**Comment by emukidid** [comment]
someone give deflicker a test please?

**Comment by emukidid** [comment]
Deflicker added for interlaced modes, more advanced video options coming in later versions.
