### ISSUE TITLE
Add sd2sp2 support on cubeSx ?

### ISSUE THREAD

**Issue by malikLeFou** [emukidid/pcsxgc#2]
Good morning!
I would like to know if it is possible to add the support sd2sp2 for the gamecube on cubesx?

Thank you

**Comment by emukidid** [comment]
This is done in current master, next release will have it.

**Comment by saulfabregwiivc** [comment]
Thanks emukidid, btw read this question: https://github.com/emukidid/pcsxgc/commit/3b149318480c4b09ec7d07ce139b0b2b8a6fbf56#commitcomment-96500664

**Comment by emukidid** [comment]
Done.
