### ISSUE TITLE
Rayman 2 - The Great Escape (USA) if using CHD crashes at DSI exception after escaping from pirate boat in first level

### ISSUE THREAD

**Issue by saulfabregwiivc** [emukidid/pcsxgc#25]
Like the title says if i use a CHD file for **Rayman 2 - The Great Escape (USA)** it crashes in a DSI exception after escaping from pirate boat in first level, on both WiiSX and WiiStation.

If using normal BIN/CUE, it works as intended.

Using latest WiiSX build with P.E.Op.S. Soft GPU.

Not sure what's happening here, any fix for this?

![image](https://github.com/emukidid/pcsxgc/assets/66485640/09965c70-0d03-412f-85b9-db006cf11a0a)

PS: On PC when i use CHD of the same game in PCSX-ReARMed it seems fine.

**Comment by saulfabregwiivc** [comment]
Unfortunately WiiSX Beta 4.0 still has this issue mentioned (crash after escaping the pirate boat if using CHD).

**Comment by pcercuei** [comment]
It seems to be a out-of-memory issue, CHD decoding is more demanding and we don't have much RAM to spare (not on GameCube anyway).

**Comment by pcercuei** [comment]
Fixed in master.

**Comment by saulfabregwiivc** [comment]
@pcercuei Thank you, it's working now with CHD.

If i'm allowed to ask you: in what file(s) did you make changes for allow Rayman 2 to not crash if using CHD?
Thanks.

Closing this issue.

**Comment by pcercuei** [comment]
I just updated to latest upstream code.
