### ISSUE TITLE
WiiSX Beta 4.0 several menu options no longer save

### ISSUE THREAD

**Issue by gamecubefan1990** [emukidid/pcsxgc#29]
On WiiSX Beta 4.0 several menu options no longer save to settings.cfg

The following options are no longer saved:
Video/ Dithering
Input/ Auto Load Slot
Audio/ Disable XA
Audio/ Disable CDDA
Audio/ Disable Reverb
Audio/ Volume

When I change the Volume it works and saves it in the settings.cfg file but when I restart WiiSX the volume is low even though the menu says loudest

**Comment by saulfabregwiivc** [comment]
Same thing happens here.

**Comment by emukidid** [comment]
Working on fixing all this currently, stay tuned.

**Comment by emukidid** [comment]
Should be fixed in #38.
