### ISSUE TITLE
Memcard and Option Saving issues with WiiSX 4.0

### ISSUE THREAD

**Issue by TheArcadeStriker** [emukidid/pcsxgc#33]
There's two things that are unfortunately hindering WiiSX from being absolutely the best with the most recent performance upgrades it has received...

The first one is that saving menu options doesn't seem to work for me. I'm unsure if whether that's something that tends to happen with USB since I only have that available (my SD card slot has issues) but even when I configure everything and hit save settings to USB repeated times, things are still unconfigured again whenever I launch the emulator again. This includes the controls as well, which I'd have to reconfigure to play with the D-Pad on the Analog Stick every time as the profile save/load doesn't seem to carry over either after a reset.

Those issues seemed to also be there with WiiSX 3.0, which is kind of annoying, but something I verified that DIDN'T happen with WiiSX 3.0 and yet does with 4.0 seems to be issues with saving memcard and savestates to USB.

Castlevania SOTN soft-locked in the save coffin silhouette spinning forever instead of eventually turning solid and closing in (which then would give the "Saved game" prompt, and before that, selecting the "save/load memcard" and "save/load state" options failed to work at all. I made sure to try this with WiiSX 3.0 and in that version both memcard and savestate saving to USB work. And yes, in 4.0 I also had set saving those to USB to no avail.

I wonder if this issue can be recreated and fixed since that's honestly the two huge glaring issues behind this being perfect (the saving issue with games in particualr is what also stops 4.0 from being the version I would stick with for single-player games that require saving).

If this can be looked at sometime soon, then it would be great, since that aside, the latest updates to WiiSX have been an absolute miracle and it has been incredible to see games like SOTN and Ridge Racer Type 4 run at 60fps on the Wii.

**Comment by saulfabregwiivc** [comment]
Could you test the latest artifacts/builds of the latest commits on https://github.com/emukidid/pcsxgc/actions?

**Comment by emukidid** [comment]
I'll look into recreating this, options failing to save is a known issue and is being worked on but I wasn't aware of the USB failures

**Comment by emukidid** [comment]
USB failures should be fixed in #38, the BIOS was being set to HLE under certain circumstances which also might've caused your other issue.
