### ISSUE TITLE
Swap CD (Disc Swap) not working on WiiSX Beta 4.0

### ISSUE THREAD

**Issue by saulfabregwiivc** [emukidid/pcsxgc#34]
Like the title says, on WiiSX the disc swap function doesn't work.

Tested these games but none of these can swap adequately the disc on WiiSX:

- Driver 2
- Vib-Ribbon
- Ridge Racer Revolution
- Metal Gear Solid
- Final Fantasy VII

Any fix for the disc swap in WiiSX? Thanks ;)

**Comment by saulfabregwiivc** [comment]
Example here for this issue: Driver 2 when prompted to load Disc 2, i use Swap CD for that but the time passes and the disc isn't changed:

![image](https://github.com/emukidid/pcsxgc/assets/66485640/c0bcb9aa-0230-4f2a-93b8-7694ad564504)

**Comment by pcercuei** [comment]
Upstream issue tracked here: https://github.com/libretro/pcsx_rearmed/issues/779

**Comment by emukidid** [comment]
This is likely fixed now too, closing.

**Comment by saulfabregwiivc** [comment]
Unfortunately latest WiiSX builds don't help, still Swap CD not working correctly:
![image](https://github.com/emukidid/pcsxgc/assets/66485640/222db3a9-8eaa-4cae-806a-4acef342ea56)

Maybe the Swap CD code is sensitive or not made for big-endian systems?

**Comment by emukidid** [comment]
I've used it in the BIOS okay but not in a game, I'll check it out.

**Comment by saulfabregwiivc** [comment]
Is there any progress in fixing this issue?

BTW, the Wii version of the PCSX-ReARMed core for RetroArch does not have this issue.

**Comment by emukidid** [comment]
Try a59dbae2942bcca9841193a65dec299c5555b030?

**Comment by saulfabregwiivc** [comment]
Tested - seems working fine Swap CD now! Closing.

**Comment by saulfabregwiivc** [comment]
Tested more games along with Driver 2 (swapping from Disc 1 to Disc 2) and Vib-Ribbon (swapping from Vib-Ribbon disc to a custom music CD) and it's working very well, thanks @emukidid!

![image](https://github.com/emukidid/pcsxgc/assets/66485640/d7086177-6350-40ad-b002-7bfdb8d3ffb0)
