### ISSUE TITLE
PCSX-ReARMed hacks from database.c not being applied on WiiSX

### ISSUE THREAD

**Issue by saulfabregwiivc** [emukidid/pcsxgc#35]
In the games which require emulator hacks in PCSX-ReARMed to be able to work (from database.c), these hacks aren't being applied in WiiSX by any reason.

Affected games by this:
- Crash Bash
- Studio33 F1 games (Formula One Arcade/99/2000/2001)
- To Heart
- Final Fantasy 4
- Digimon World
- all the games mentioned here: https://github.com/emukidid/pcsxgc/blob/master/pcsx_rearmed/libpcsxcore/database.c

Any fix? Thanks for the huge progress in this emulator :D

**Comment by pcercuei** [comment]
Studio33 games work perfectly fine in WiiSX 4.0, so the database.c hacks are definitely applied.

What makes you think they are not?

**Comment by saulfabregwiivc** [comment]
> Studio33 games work perfectly fine in WiiSX 4.0, so the database.c hacks are definitely applied.
> 
> What makes you think they are not?

Crash Bash is not applying the hack for GPU Slow linked list processing (still no text in the pause menu).

**Comment by pcercuei** [comment]
Formula One Arcade SCES03886 works fine here.

**Comment by saulfabregwiivc** [comment]
I'll try it later or tomorrow again and i'll tell my results.

**Comment by pcercuei** [comment]
> Crash Bash is not applying the hack for GPU Slow linked list processing (still no text in the pause menu).

Ok, I can reproduce that one at least. The fix is a one-liner (just a libpcsxcore config option to enable), but it causes another bug further down.

**Comment by saulfabregwiivc** [comment]
GPU Slow linked list processing is applied now, thanks!

![image](https://github.com/emukidid/pcsxgc/assets/66485640/7627ed4f-0e35-4111-850f-d186b5caa472)

**Comment by saulfabregwiivc** [comment]
And the crash at Studio33 F1 games doesn't happen anymore on WiiSX.
