### ISSUE TITLE
No Analog Controls

### ISSUE THREAD

**Issue by gamecubefan1990** [emukidid/pcsxgc#39]
Thanks for the further development of this great emulator, the Audio Volume and Video settings are now saved on SD/USB.
But there is a new problem: When I select "Analog" under PSX Controller Type, the Analog Stick and C Stick on the Gamecube Controller don't work.
WiiSX Beta 4 and older versions have no issues with the "Analog" setting when setting the PSX Controller Type.
I use an original Nintendo GameCube Controller.

**Comment by emukidid** [comment]
yep, I'll have a look. We haven't been populating some structs that the core expects and that's why this is behaving the way that it is.

**Comment by emukidid** [comment]
This should be fixed now. I'll expand on controller configuration and fix lightgun support soon too.
