### ISSUE TITLE
Analog Controls have left drift

### ISSUE THREAD

**Issue by gamecubefan1990** [emukidid/pcsxgc#41]
Since Beta 4, the controller has a left drift when using the PSX Controller Type setting to Analog.
The best game where you can see it is S.C.A.R.S. When you start a race, the car steers slightly to the left.
If you set the controls from "Analog" to "Standard" so that the analog stick doesn't work, the car will drive straight.
In Beta 3 it runs perfectly and without drift when you set the controls to “Analog”.
I use an original GameCube controller.

EDIT: It seems that this doesn't affect all games.
I played Need for Speed 2, Crash Bandicoot 2, Croc and some other games, I didn't notice any drift there.

**Comment by emukidid** [comment]
Can you check this on the libretro pcsx_rearmed core for RetroArch? (grab the latest)

**Comment by gamecubefan1990** [comment]
I installed the latest version of RetroArch on my Samsung Galaxy S22 and downloaded the current core from pcsx_rearmed.
It seems the same problem exists there.
If you set the controls from "Standard" to "Analog", the car steers slightly to the left.
I think the error is only in the game “S.C.A.R.S.”.
I can't detect any drift in other games like South Park Rally, Muppet RaceMania or the Need for Speed series.

**Comment by pcercuei** [comment]
Thanks, that's useful.

Can you open a bug report here? https://github.com/libretro/pcsx_rearmed/issues

**Comment by saulfabregwiivc** [comment]
This issue was also present in PCSX-ReARMed (https://github.com/libretro/pcsx_rearmed/issues/792) and it also was fixed so far in: https://github.com/libretro/pcsx_rearmed/commit/c396a646b9ce3082bc6aee7da35219f6424c99b6

**Comment by emukidid** [comment]
Should be fixed in 447b7aa1223374a868ab193c63df609bfcf806ad
