### ISSUE TITLE
WIISX Beta 4 Random crashes when returning to menu

### ISSUE THREAD

**Issue by gamecubefan1990** [emukidid/pcsxgc#44]
Since WiiSX Beta 4, the emulator sometimes crashes when you are playing a game and want to return to the emulator menu.
No code dump error is displayed, the gameplay freezes and you have to hard reset the Wii.
I tested it with 28 games (PAL) and it can happen with any game.
If it doesn't crash the first time, you can trigger it by going to "Resume Game" in the emulator menu then when you're back in the game go back to the emulator menu and do this process several times until it freezes.
WiiSX Beta 3 and 2.1 do not have this problem, other emulators such as WiiSXRX and Wii64 also have no problems when you return to the emulator menu.
I tested it on 2 different Pal Wii consoles with component (480p) cable, 3 different SD cards and GameCube controller.

**Comment by gamecubefan1990** [comment]
I don't know if it helps, but I downloaded different versions under the Github Actions tab and the problem starts with commit fab79af "Triple buffering (#26)".

**Comment by emukidid** [comment]
I've noticed this too, mostly on my PAL GameCube.

**Comment by gamecubefan1990** [comment]
Unfortunately I don't know anything about programming, but I noticed that it occurs from commit fab79af, the commit d681a2f which was a few days before works without this error.
Maybe you can find the error faster this way.

**Comment by emukidid** [comment]
Found a likely cause, Async rendering, it's way more frequently triggered when you have no FPS limit set

**Comment by emukidid** [comment]
Should be fixed by 8b7b29a233ac4eb3468d4af9c7b990d0c0c253a8
