### ISSUE TITLE
Trouble Launching any .bin game.

### ISSUE THREAD

**Issue by MasterBigCat** [emukidid/pcsxgc#48]
Every time i try to load up a .bin game it just starts like a normal ps1 console but then goes immediately to the memory card/cd player screen?  Not sure as to why it wont even bother trying to load any game. It just does that with every game i try" Again I'm just picking any ps1 .bin that used to load up with your april updated version of the old wii sx but with the new .dol of 4.1 and it wont actually load the file enough to even start any game. I have the correct bios and everything. So i have a setting set wrong or something? Any help would be great!

**Comment by MasterBigCat** [comment]
I should have mentioned im using the cube version on swiss not wii. If that makes any difference to helping figure out my problem.

**Comment by emukidid** [comment]
hmm, do you have "Boot through BIOS" set to yes? Try setting it to "No".

**Comment by MasterBigCat** [comment]
> hmm, do you have "Boot through BIOS" set to yes? Try setting it to "No".

That did make it work, i tried it before but didnt realize theres supposed to be 10 seconds of black screen. I thought it wasnt working and only waited till around 8 seconds before quitting back to emulator. Thank you
