### ISSUE TITLE
Memory card problems

### ISSUE THREAD

**Issue by svk77** [emukidid/pcsxgc#49]
GameCube USA Dol-001, picoboot, swiss, fat32 sd card slot2 adapter.
Latest CubeSX-4.1

Gran Turismo 2  USA SCUS-94455 just doesn't see memory cards. When you start the game, memory cards are created, and they are on the SD card, in the saves folder. But the game doesn't see them.

Gran Turismo EUR  SCES-00984 - sees memory cards and allows you to write. But after the first recording, when reloading the game, when loading data from the memory card, the emulator crashes into Swiss.

The SD card is not fragmented. There are no problems with other applications.
All emulator settings are by default, except for the enabled analog control (bios hle, etc.).

**Comment by pcercuei** [comment]
@svk77 so this is with the HLE bios? Try with a real PS1 BIOS.

**Comment by svk77** [comment]
> @svk77 so this is with the HLE bios? Try with a real PS1 BIOS.

hmm... really, my fault...
The thing is that I already tried using a real bios, but I tried it before, it is not related to the problem stated. At that time it seemed to me that the emulator was frozen, but in fact I just needed to wait a little longer.
Okay, I tried the bios scph9002(7502).bin, and there is no problem - the above games work fine with the memory card.
It would be nice to add a couple of lines about this in the readme.
Question closed =)

**Comment by pcercuei** [comment]
It is mentioned in PCSX' README.md: https://github.com/emukidid/pcsxgc/blob/master/pcsx_rearmed/README.md

These issues are from the upstream emulator, so they are not specific to WiiSX / CubeSX. You can open the issue on the upstream project page, https://github.com/libretro/pcsx_rearmed/issues

**Comment by svk77** [comment]
@pcercuei  OK OK
I’ve been using emulators for years (I’m 47, I launched my first emulator in 2000), but here I missed =)
shit happens

**Comment by pcercuei** [comment]
No problem, it's great seeing people testing on the GameCube.
